Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -20,10 +20,14 @@ jobs:
 
          - name: Setup SSH Key
            run: |
-              mkdir -p ~/.ssh
-              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-              chmod 400 ~/.ssh/id_rsa
-              ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts
+             mkdir -p ~/.ssh
+             echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+             chmod 400 ~/.ssh/id_rsa
+             if [ -z "${{ secrets.HOST_IP }}" ]; then
+               echo "Error: HOST_IP is not set."
+               exit 1
+             fi
+             ssh-keyscan -H "${{ secrets.HOST_IP }}" >> ~/.ssh/known_hosts
            shell: bash
 
          - name: Connect to GCP and Deploy
